### ISSUE TITLE
[1.17 Draft] Weird Codec/JSON-related Bug

### ISSUE THREAD

**Issue by sylv256** [hYdos/Lint#80]
## Description
This could possibly be a registry or JSON bug, but I'm not sure. The error doesn't tell me the file that failed to parse; it only tells me that it failed.

## To Reproduce

1. Compile and run [this Lint fork](https://github.com/TehcJS/Lint/tree/bcdb86619e8954ece6b7e5c695edafbdabd008c1)
2. Once the title screen has appeared, select "Singleplayer"
3. Check the console

## Expected Behavior
The singleplayer world creation screen should show when the "Singleplayer" button on the title screen is clicked.

## Screenshots/Logs
https://hastebin.com/eficirecep.sql
The error can be found here:
```java
[11:49:26] [Render thread/ERROR] (Minecraft) Feature: Not a JSON object: "lint:dills"; Not a JSON object: "lint:watermints"; Not a JSON object: "lint:spearmints"; Not a JSON object: "lint:taterbanes"; Not a JSON object: "lint:mystical_stems"; Not a JSON object: "lint:mystical_grass"; Not a JSON object: "lint:mystical_flowers"; Not a JSON object: "lint:frozen_trees"
[11:49:27] [Render thread/WARN] (FileUtil) Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[11:49:27] [Render thread/FATAL] (Minecraft) Reported exception thrown!
 net.minecraft.util.crash.CrashException: mouseClicked event handler
	
Caused by: com.google.gson.JsonParseException: Error loading registry data: Max must be at least min, min_inclusive: 2, max_inclusive: 1
	at net.minecraft.util.registry.DynamicRegistryManager.method_34849(DynamicRegistryManager.java:221) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistryManager.load(DynamicRegistryManager.java:221) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.util.registry.DynamicRegistryManager.load(DynamicRegistryManager.java:212) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.util.dynamic.RegistryOps.method_36575(RegistryOps.java:57) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.util.registry.DynamicRegistryManager.create(DynamicRegistryManager.java:174) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.create(CreateWorldScreen.java:142) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget.filter(WorldListWidget.java:103) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget.<init>(WorldListWidget.java:85) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.gui.screen.world.SelectWorldScreen.init(SelectWorldScreen.java:63) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:387) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient.java:986) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.method_19861(TitleScreen.java:144) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:40) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:16) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:121) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:27) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.mouseClicked(TitleScreen.java:311) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:94) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:490) ~[minecraft-1.17-project-@-mapped-net.fabricmc.yarn-1.17+build.11-v2.jar:?]

## Specifications
Operating System | Minecraft Version | Mod Version
---------------- | ----------------- | -----------
Linux Ubuntu 20.04 | 1.17 | 2.0.0-SNAPSHOT+1.17 (#77)

## Additional Context
N/A

**Comment by sylv256** [comment]
Fixed. This was related to method argument changes causing incorrect registry.
